"""Create solicitation table

Revision ID: 1a542990513e
Revises: 5dc4d862d8fc
Create Date: 2026-04-09 02:43:19.635003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a542990513e'
down_revision: Union[str, Sequence[str], None] = '5dc4d862d8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('papel', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('participantes', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=True),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('fk_sala', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=True),
    sa.Column('motivo_recusa', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fk_sala'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_email'), 'solicitacoes', ['email'], unique=False)
    op.create_index(op.f('ix_solicitacoes_id'), 'solicitacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacoes_id'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_email'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    # ### end Alembic commands ###
