"""link allocation to professor and discipline

Revision ID: 2ae1dba1e9ea
Revises: cf4bc424b5c2
Create Date: 2026-04-09 01:43:38.628797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae1dba1e9ea'
down_revision: Union[str, Sequence[str], None] = 'cf4bc424b5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alocacao', sa.Column('fk_professor', sa.Integer(), nullable=True))
    op.add_column('alocacao', sa.Column('fk_disciplina', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alocacao', 'disciplinas', ['fk_disciplina'], ['id'])
    op.create_foreign_key(None, 'alocacao', 'professores', ['fk_professor'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alocacao', type_='foreignkey')
    op.drop_constraint(None, 'alocacao', type_='foreignkey')
    op.drop_column('alocacao', 'fk_disciplina')
    op.drop_column('alocacao', 'fk_professor')
    # ### end Alembic commands ###
