"""Add course and period tracking to alocacao

Revision ID: 4a4c65659819
Revises: 63d4f3dffaa5
Create Date: 2026-04-09 02:15:24.747833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4c65659819'
down_revision: Union[str, Sequence[str], None] = '63d4f3dffaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alocacao', sa.Column('fk_curso', sa.Integer(), nullable=True))
    op.add_column('alocacao', sa.Column('fk_periodo', sa.Integer(), nullable=True))
    op.add_column('alocacao', sa.Column('dia_semana', sa.String(length=20), nullable=True))
    op.add_column('alocacao', sa.Column('data_inicio', sa.DateTime(), nullable=True))
    op.add_column('alocacao', sa.Column('data_fim', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'alocacao', 'cursos', ['fk_curso'], ['id'])
    op.create_foreign_key(None, 'alocacao', 'periodos', ['fk_periodo'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alocacao', type_='foreignkey')
    op.drop_constraint(None, 'alocacao', type_='foreignkey')
    op.drop_column('alocacao', 'data_fim')
    op.drop_column('alocacao', 'data_inicio')
    op.drop_column('alocacao', 'dia_semana')
    op.drop_column('alocacao', 'fk_periodo')
    op.drop_column('alocacao', 'fk_curso')
    # ### end Alembic commands ###
