"""Expand user model with profiles and status

Revision ID: 5dc4d862d8fc
Revises: 4a4c65659819
Create Date: 2026-04-09 02:22:29.022280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc4d862d8fc'
down_revision: Union[str, Sequence[str], None] = '4a4c65659819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('matricula', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('curso', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('siape', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('departamento', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('status', sa.String(length=20), server_default=sa.text("'pendente'"), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'status')
    op.drop_column('usuarios', 'departamento')
    op.drop_column('usuarios', 'siape')
    op.drop_column('usuarios', 'curso')
    op.drop_column('usuarios', 'matricula')
    op.drop_column('usuarios', 'telefone')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###
