"""Add periodos table and align schemas

Revision ID: 63d4f3dffaa5
Revises: 2ae1dba1e9ea
Create Date: 2026-04-09 02:06:19.870853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d4f3dffaa5'
down_revision: Union[str, Sequence[str], None] = '2ae1dba1e9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodos_id'), 'periodos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodos_id'), table_name='periodos')
    op.drop_table('periodos')
    # ### end Alembic commands ###
