"""update fk_professor

Revision ID: a4158691be0f
Revises: 930aafffb48a
Create Date: 2026-05-03 15:16:43.840172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4158691be0f'
down_revision: Union[str, Sequence[str], None] = '930aafffb48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alocacao_fk_professor_fkey'), 'alocacao', type_='foreignkey')
    op.create_foreign_key(None, 'alocacao', 'usuarios', ['fk_professor'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alocacao', type_='foreignkey')
    op.create_foreign_key(op.f('alocacao_fk_professor_fkey'), 'alocacao', 'professores', ['fk_professor'], ['id'])
    # ### end Alembic commands ###
